### ISSUE TITLE
Push latest wire protocol code

### ISSUE THREAD

**Issue by ranxian** [larryxiao/peloton#77]
@sid1607 
@omegaga 
Hello Siddarth, can you push the latest wire protocol code so that @omegaga can work on the new frontend over the weekends? Thanks

**Comment by sid1607** [comment]
@ranxian 

Hello Ryan. Which repository do you want me to push to? Peloton-frontend or cmudb/peloton?

**Comment by ranxian** [comment]
@sid1607 Just push to this repository, it would suffice. Thanks!

**Comment by sid1607** [comment]
@ranxian 
@omegaga 
I have pushed the latest changes to the "wire" branch - https://github.com/larryxiao/peloton/tree/wire
